name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'extension/.nvmrc'
        cache: 'npm'
        cache-dependency-path: 'extension/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./extension
      run: npm ci
    
    - name: Type check
      working-directory: ./extension
      run: npm run compile